url: "https://www.lsa-transports.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

sass:
  sass_dir: css

markdown: kramdown


title: "Lesaffre Service Assistance | Taxi | TPMR | Minicar | Minibus"
description: "Situés à Montfort/Meu, Monterfil et Iffendic, nous assurons vous déplacements de 1 à 20 passagers. Professionnels ou particuliers, transports de groupes."
logo: /assets/images/logoLSA.png
locale: "Fr"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
